_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
AUG:
    value:
        COLOR_JITTER: 0.4
        RAND_AUGMENT: rand-m9-mstd0.5-inc1
BASE:
    value:
        - ""
DATA:
    value:
        BATCH_SIZE: 64
        DATA_PATH: ""
        DATASET: cifar10
        IMG_SIZE: 32
        INTERPOLATION: bicubic
        NUM_WORKERS: 32
        PIN_MEMORY: true
EVAL_MODE:
    value: false
MODEL:
    value:
        DROP_RATE: 0
        NAME: lenet
        NUM_CLASSES: 10
        RESUME: ""
OUTPUT:
    value: output/lenet
PRINT_FREQ:
    value: 99999
SAVE_FREQ:
    value: 5
SEED:
    value: 0
TEST:
    value:
        CROP: true
        SEQUENTIAL: false
        SHUFFLE: false
TRAIN:
    value:
        ACCUMULATION_STEPS: 1
        EPOCHS: 20
        LR: 0.007568304298229739
        LR_SCHEDULER:
            NAME: cosine
        MIN_LR: 3e-05
        OPTIMIZER:
            BETAS:
                - 0.9
                - 0.999
            EPS: 1e-08
            MOMENTUM: 0.9540690887792035
            NAME: adamw
        START_EPOCH: 0
        WARMUP_EPOCHS: 10
        WARMUP_LR: 3e-05
